set -g @plugin 'tmux-plugins/tmux-resurrect'

# Vi mode-keys
set-window-option -g mode-keys vi

# Vi visual mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'Escape' send -X cancel

set -g mouse on

set-option -g focus-events on
set-option -sg escape-time 10

set-option -g status-right ""
set-option -sa terminal-overrides ',xterm-256color:RGB'
set-option -g status-style bg=default
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
